
DROP TABLE IF EXISTS shipments;

CREATE TABLE shipments (
    "DATE" TEXT,
    "YEAR" INTEGER,
    "MONTH" INTEGER,
    "HSN_CODE" TEXT,
    "GOODS_DESCRIPTION" TEXT,
    "UNIT" TEXT,
    "STD_UNIT" TEXT,
    "QUANTITY" REAL,
    "TOTAL_VALUE_INR" REAL,
    "DUTY_PAID_INR" REAL,
    "GRAND_TOTAL_INR" REAL,
    "LANDED_COST_PER_UNIT" REAL,
    "EXTRACTED_MODEL" TEXT,
    "EXTRACTED_MATERIAL" TEXT,
    "CATEGORY" TEXT,
    "SUB_CATEGORY" TEXT,
    "SUPPLIER_NAME" TEXT
);